### ISSUE TITLE
Fix code scanning alert - Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by Horusprg** [Colab-UNIRIO-UFPA/uxtracking.com#46]
Tracking issue for:
- [x] https://github.com/Colab-UNIRIO-UFPA/uxtracking.com/security/code-scanning/33

**Comment by Williane28** [comment]
`@app.route("/dataview/<username>/", methods=["GET", "POST"])
@app.route("/dataview/<username>/<plot>", methods=["GET", "POST"])
def dataview(username, plot=None):
    if request.method == "POST":
        if "username" in session:
            # faz a leitura da base de dados de coletas do usuário
            userfound = db.users.find_one({"username": session["username"]})
            userid = userfound["_id"]
            datadir = f"./Samples/{userid}"

            dir = request.form["dir"]

            #normalizando caminho base
            base_path = os.path.normpath(datadir)

            #normalizando caminho completo
            folder = os.path.normpath(os.path.join(base_path, dir))

            if not folder.startswith(base_path):
                raise Exception("not allowed")`
